ccd:
  enabled: false
postgresql:
  enabled: false
idam-pr:
  enabled: false
xui-webapp:
  enabled: false
camunda-bpm:
  enabled: false
civil-service:
  enabled: false
civil-wa:
  enabled: false
servicebus:
  enabled: false
