civil-ga-ccd-stack:
  enabled: false
postgresql:
  enabled: false
idam-pr:
  enabled: false
xui-webapp:
  enabled: false
camunda-bpm:
  enabled: false
civil-service:
  enabled: false
wa:
  enabled: false
  taskBatchCron:
    enabled: false
  reconfigurationBatchCron:
    enabled: false
  terminationBatchCron:
    enabled: false
servicebus:
  enabled: false
